src/controllers/DocsController.php
<?php

namespace app\controllers;

use Yii;
use yii\web\Controller;

class DocsController extends Controller
{

    public function actionIndex()
    {
        return $this->render('index');
    }

    public function actionBowerCli()
    {
        return $this->render('bower-cli');
    }

    public function actionBowerFormat()
    {
        return $this->render('bower-format');
    }

    public function actionUpdateWebhook()
    {
        return $this->render('update-webhook');
    }

    public function actionRegistryCurl()
    {
        return $this->render('registry-curl');
    }

    public function actionSemver()
    {
        return $this->render('semver');
    }

}

src/controllers/ModController.php
<?php

namespace app\controllers;

use app\components\Git;
use Yii;
use app\models\Package;
use app\models\search\PackageSearch;
use yii\db\Expression;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * ModController implements the CRUD actions for Package model.
 */
class ModController extends Controller
{
    /**
     * @var bool
     */
    public $enableCsrfValidation = false;

    /**
     * Browse Package models.
     * @return mixed
     */
    //public function actionIndex()
    //{
    //    $searchModel = new PackageSearch();
    //    $dataProvider = $searchModel->search(['PackageSearch' => Yii::$app->request->queryParams]);
    //
    //    return $this->render('index', [
    //        'searchModel' => $searchModel,
    //        'dataProvider' => $dataProvider,
    //    ]);
    //}

    /**
     * Redirects to a random mod.
     * @return mixed
     */
    //public function actionRandom()
    //{
    //    $driver = Package::getDb()->driverName;
    //    if ($driver == 'mysql') {
    //        $rand = new Expression('RAND()');
    //    } elseif ($driver == 'pgsql') {
    //        $rand = new Expression('RANDOM()');
    //    } else {
    //        return $this->redirect(['index']);
    //    }
    //    $model = Package::find()->orderBy($rand)->one();
    //    return $this->redirect(['view', 'name' => $model->name]);
    //}

    /**
     * Displays a single Package model.
     * @param string $name
     * @return mixed
     * @throws NotFoundHttpException
     */
    public function actionView($name)
    {
        $model = $this->findModel($name);

        // add a hit once per user per 24 hours
        $cacheKey = $model->name . '_' . Yii::$app->request->userIP;
        if (!Yii::$app->cache->get($cacheKey)) {
            Yii::$app->cache->set($cacheKey, true, (60 * 60 * 24));
            $model->hits++;
            $model->save(false, ['hits']);
        }

        return $this->render('view', [
            'model' => $model,
        ]);
    }

    /**
     * Displays a single Package models bower info.
     * @param string $name
     * @return mixed
     * @throws NotFoundHttpException
     */
    public function actionBower($name)
    {
        $model = $this->findModel($name);
        return $this->render('bower', [
            'model' => $model,
        ]);
    }

    /**
     * Displays a single Package models readme info.
     * @param string $name
     * @return mixed
     * @throws NotFoundHttpException
     */
    public function actionReadme($name)
    {
        $model = $this->findModel($name);
        return $this->render('readme', [
            'model' => $model,
        ]);
    }

    /**
     * Displays a single Package models readme info.
     * @param string $name
     * @return mixed
     * @throws NotFoundHttpException
     */
    public function actionScreenshots($name)
    {
        $model = $this->findModel($name);
        return $this->render('screenshots', [
            'model' => $model,
        ]);
    }

    /**
     * Creates a new Package model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Package();

        if ($model->load(Yii::$app->request->post()) && $model->harvestModInfo() && $model->save()) {
            Yii::$app->getSession()->setFlash('success', Yii::t('app', 'Mod has been registered.'));
            return $this->redirect(['view', 'name' => $model->name]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Package model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param string $name
     * @return mixed
     * @throws NotFoundHttpException
     * @throws \Exception
     * @throws \Throwable
     * @throws \yii\db\StaleObjectException
     */
    public function actionUpdate($name)
    {
        $model = $this->findModel($name);
        if (Git::getFile($model->url)) {
            $model->harvestModInfo();
            if ($model->getDirtyAttributes()) {
                if ($model->save()) {
                    Yii::$app->getSession()->setFlash('success', Yii::t('app', 'Mod has been updated from remote repository.'));
                } else {
                    Yii::$app->getSession()->setFlash('danger', Yii::t('app', 'Error while saving mod updates.'));
                }
            } else {
                Yii::$app->getSession()->setFlash('info', Yii::t('app', 'Mod has been updated from remote repository, however no change was detected.'));
            }
            return $this->redirect(['view', 'name' => $model->name]);
        }
        $model->delete();
        Yii::$app->getSession()->setFlash('danger', Yii::t('app', 'Mod source could not be found updated so mod was deleted.'));
        return $this->redirect(Yii::$app->homeUrl);
    }


    /**
     * Renders a tag cloud of popular keywords
     * @return mixed
     */
    //public function actionCloud()
    //{
    //    $keywords = Yii::$app->cache->get('mod.cloud.keywords');
    //    if (!$keywords) {
    //        $keywords = [];
    //        $packages = Package::find()->where(['is not', 'keywords', null])->all();
    //        foreach ($packages as $package) {
    //            foreach (explode(',', $package->keywords) as $keyword) {
    //                if (!isset($keywords[$keyword])) {
    //                    $keywords[$keyword] = [
    //                        'text' => $keyword,
    //                        'weight' => 0,
    //                        'link' => Url::to(['/mod/index', 'search' => $keyword]),
    //                    ];
    //                }
    //                $keywords[$keyword]['weight']++;
    //            }
    //        }
    //        Yii::$app->cache->set('mod.cloud.keywords', $keywords, 60 * 60);
    //    }
    //    return $this->render('cloud', ['keywords' => $keywords]);
    //}

    /**
     * Finds the Package model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param string $name
     * @return Package the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($name)
    {
        if (($model = Package::find()->where(['name' => $name])->one()) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

src/views/docs/bower-cli.php
<?php

/* @var $this yii\web\View */

use yii\bootstrap\Nav;
use yii\helpers\Html;

$this->title = 'Bower CLI';
$this->params['breadcrumbs'][] = ['label' => 'Docs', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="docs-install">

    <h1>Using Bower to Manage Mods</h1>

    <p>You can use Bower to install Minetest mods and dependency mods quickly
        and easily under Linux, Windows, and Mac OS X. Bower needs primarily two software packages named
        <a href="http://nodejs.org/">NodeJS</a> and <a href="http://git-scm.com/">Git</a>, which are easy to install.</p>

    <h2>Installation</h2>

    <div class="row">
        <div class="col-lg-4">
            <h2>Windows</h2>

            <ol>
                <li>Download and install <a href="http://nodejs.org/">nodejs</a>.</li>
                <li>Download and install <a href="http://git-scm.com/download/win">git</a>.</li>
            </ol>

            <p>Install bower</p>
            <pre class="prettyprint lang-bash">C:\> npm install -g bower</pre>

        </div>
        <div class="col-lg-4">
            <h2>Mac</h2>

            <ol>
                <li>Download and install <a href="http://nodejs.org/">nodejs</a>.</li>
                <li>Download and install <a href="http://git-scm.com/download/mac">git</a>.</li>
            </ol>

            <p>Install bower</p>
            <pre class="prettyprint lang-bash">$ npm install -g bower</pre>

        </div>
        <div class="col-lg-4">
            <h2>Ubuntu/Debian</h2>

            <p>Install nodejs, npm and git</p>
            <pre class="prettyprint lang-bash">$ sudo apt-get install nodejs npm git-core</pre>

            <p>Ubuntu users, link nodejs to node</p>
            <pre class="prettyprint lang-bash">$ sudo ln -s /usr/bin/nodejs /usr/bin/node</pre>

            <p>Install bower</p>
            <pre class="prettyprint lang-bash">$ sudo npm install -g bower</pre>

        </div>
    </div>

    <h2>Configuration</h2>

    <p>In order to connect to the minetest-bower registry you need to configure bower.</p>

    <p>Create a
        <code>.bowerrc</code> file in your home directory or minetest folder with the following contents.
    </p>
                <pre class="prettyprint lang-js">{
    "registry": "https://minetest-bower.herokuapp.com/",
    "directory" : "mods"
}</pre>

    <h2>Usage</h2>

    <div class="row">
        <div class="col-md-4">
            <h3>Install Mods</h3>

            <p>Install mods and their dependencies with <code>bower install</code>.</p>
            <pre class="prettyprint lang-bash">$ bower install &lt;mod&gt;</pre>
        </div>
        <div class="col-md-4">
            <h3>Search Mods</h3>

            <p>Find mods that you can install with
                <code>bower search</code> or <?= Html::a('browse the repository', ['/mod/index']) ?>.</p>
            <pre class="prettyprint lang-bash">$ bower search &lt;keyword&gt;

# for example
$ bower search rainbow</pre>
        </div>
        <div class="col-md-4">
            <h3>Register Mods</h3>

            <p>Register mods with
                <code>bower register</code> or <?= Html::a('submit a mod online', ['/mod/create']) ?>.</p>
            <pre class="prettyprint lang-bash">$ bower register &lt;my_mod_name&gt; &lt;git_endpoint&gt;

# for example
$ bower register rainbows https://github.com/user/rainbows.git</pre>

            <p>Optionally, to add more information about your mod such as description, screenshots, authors and
                licence, you can submit a JSON file along with your mod. To do so add a
                <code>bower.json</code> file to to your mod's git repository. For the format to be
                used, <?= Html::a('click here', ['/docs/bower-format']); ?>.
            </p>
        </div>
    </div>

</div>

src/views/docs/bower-format.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'bower.json Format';
$this->params['breadcrumbs'][] = ['label' => 'Docs', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="docs-bower-json-format">

    <h1><?= Html::encode($this->title) ?></h1>

    <h2>Example <code>bower.json</code></h2>

    <pre class="prettyprint lang-js">{
  "name": "rainbows",
  "description": "Description of my minetest mod.",
  "keywords": [
    "rainbows"
  ],
  "homepage": "http://example.com/",
  "forum": "https://forum.minetest.net/viewtopic.php?id=1",
  "screenshots": [
    "http://example.com/screenshot.png"
  ],
  "authors": [
    "Author &lt;author@example.com&gt;"
  ],
  "license": "WTFPL",
  "dependencies": {
    "some_mod": "~1.2.3",
    "another_mod": "~4.2.11"
  },
  "ignore": [
    "**/.*",
    "mods",
    "test"
  ]
}</pre>

    <h2>Specifications</h2>

    <h3><code>name</code></h3>

    <p><strong>Required</strong></p>

    <p>Type: <code>String</code></p>

    <p>The name of the package as stored in the registry.</p>
    <ul>
        <li>Must be unique.</li>
        <li>Should be slug style for simplicity, consistency and compatibility. Example: <code>unicorn_cake</code></li>
        <li>Lowercase, a-z, can contain digits, 0-9, can contain dash or dot but not start/end with them.</li>
        <li>Consecutive dashes or dots not allowed.</li>
        <li>50 characters or less.</li>
    </ul>


    <h3><code>description</code></h3>

    <p><strong>Recommended</strong></p>

    <p>Type: <code>String</code></p>

    <p>Any character. Max 140.</p>

    <p>Help users identify and search for your package with a brief description. Describe what your package does, rather than what it's made of. Will be displayed in search/lookup results on the CLI and the website that can be used to search for packages.</p>


    <h3><code>keywords</code></h3>

    <p><strong>Recommended</strong></p>

    <p>Type: <code>Array</code> of <code>String</code></p>

    <p>Same format requirements as <code>name</code>.</p>

    <p>Used for search by keyword. Helps make your package easier to discover without people needing to know its name.</p>


    <h3><code>homepage</code></h3>

    <p><strong>Recommended</strong></p>

    <p>Type: <code>String</code></p>

    <p>URL to learn more about the package. Falls back to GitHub/BitBucket project if not specified and it's a GitHub or BitBucket endpoint.</p>


    <h3><code>forum</code></h3>

    <p><strong>Recommended</strong></p>

    <p>Type: <code>String</code></p>

    <p>URL to discuss the package.</p>


    <h3><code>screenshots</code></h3>

    <p><strong>Recommended</strong></p>

    <p>Type: <code>Array</code> of <code>String</code></p>

    <p>Used to display screenshots of your package.</p>


    <h3><code>authors</code></h3>

    <p><strong>Recommended</strong></p>

    <p>Type: <code>Array</code> of (<code>String</code> or <code>Object</code>)</p>

    <p>A list of people that authored the contents of the package.</p>

    <p>Either:</p>

    <pre class="prettyprint lang-js">"authors": [
    "John Doe",
    "John Doe &lt;john@doe.com&gt;",
    "John Doe &lt;john@doe.com&gt; (http://johndoe.com)"
]</pre>

    <p>or:</p>

    <pre class="prettyprint lang-js">"authors": [
    { "name": "John Doe" },
    { "name": "John Doe", "email": "john@doe.com" },
    { "name": "John Doe", "email": "john@doe.com", "homepage": "http://johndoe.com" }
]</pre>


    <h3><code>license</code></h3>

    <p><strong>Recommended</strong></p>

    <p>Type: <code>String</code> or <code>Array</code> of <code>String</code></p>

    <p><a href="https://spdx.org/licenses/">SPDX license identifier</a> or path/url to a license.</p>


    <h3><code>dependencies</code></h3>

    <p><strong>Optional</strong></p>

    <p>Type: <code>Object</code></p>

    <p>Dependencies are specified with a simple hash of package name to a semver compatible identifier or URL.</p>

    <ul>
        <li>Key must be a valid <code>name</code>.</li>
        <li>Value must be a valid
            <a href="https://github.com/npm/node-semver#ranges">semver range</a>, a Git URL, or a URL (inc. tarball and zipball).
        </li>
        <li>Git URLs can be restricted to a reference (revision SHA, branch, or tag) by appending it after a hash, e.g.
            <code>https://github.com/owner/package.git#branch</code>.
        </li>
        <li>Value can be an owner/package shorthand, i.e. owner/package. By default, the shorthand resolves to GitHub -> git://github.com/owner/package.git. This may be changed in
            <code>.bowerrc</code> <a href="http://bower.io/docs/config/#shorthand-resolver">shorthand_resolver</a>.
        </li>
        <li>Local paths may be used as values for local development, but they will be disallowed when registering.</li>
    </ul>


    <h3><code>ignore</code></h3>

    <p><strong>Recommended</strong></p>

    <p>Type: <code>Array</code> of <code>String</code></p>

    <p>A list of files for Bower to ignore when installing your package.</p>

    <p>Note: symbolic links will always be ignored. However `bower.json` will never be ignored.</p>

    <p>The ignore rules follow the same rules specified in the
        <a href="http://git-scm.com/docs/gitignore">gitignore pattern spec</a>.</p>


</div>

src/views/docs/index.php
<?php

/* @var $this yii\web\View */

use yii\bootstrap\Nav;
use yii\helpers\Html;

$this->title = 'Documentation';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="docs-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= Nav::widget([
        'items' => [
            ['label' => 'Bower CLI', 'url' => ['/docs/bower-cli']],
            ['label' => 'bower.json Format', 'url' => ['/docs/bower-format']],
            ['label' => 'Update Webhook', 'url' => ['/docs/update-webhook']],
            ['label' => 'Semantic Versioning', 'url' => ['/docs/semver']],
            ['label' => 'Registry Requests using cURL', 'url' => ['/docs/registry-curl']],
        ],
    ]) ?>

</div>

src/views/docs/registry-curl.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'Registry Requests using cURL';
$this->params['breadcrumbs'][] = ['label' => 'Docs', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="docs-registry-curl">

    <h1><?= Html::encode($this->title) ?></h1>

    <h2>Create Mod</h2>

    <pre class="prettyprint lang-bash">curl https://minetest-bower.herokuapp.com/packages -v -F 'name=rainbows' -F 'url=https://github.com/user/rainbows.git'</pre>

    <h2>Find Mod</h2>

    <pre class="prettyprint lang-bash">curl https://minetest-bower.herokuapp.com/packages/rainbows</pre>

    <p>returns:</p>

    <pre class="prettyprint lang-js">{"name":"rainbows","url":"https://github.com/user/rainbows.git"}</pre>

    <h2>Search Mod</h2>

    <pre class="prettyprint lang-bash">curl https://minetest-bower.herokuapp.com/packages/search/rainbows</pre>

    <p>returns:</p>

    <pre class="prettyprint lang-js">[{"name":"rainbows","url":"https://github.com/user/rainbows.git"}, {"name":"rainbows_lib","url":"git://github.com/user/rainbows_lib.git"}]</pre>

</div>

src/views/docs/semver.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'Semantic Versioning';
$this->params['breadcrumbs'][] = ['label' => 'Docs', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="docs-bower-json-format">

    <h1><?= Html::encode($this->title) ?></h1>


    <h2>Summary</h2>

    Given a version number MAJOR.MINOR.PATCH, increment the:

    <ul>
        <li>MAJOR version when you make incompatible API changes,</li>
        <li>MINOR version when you add functionality in a backwards-compatible manner, and</li>
        <li>PATCH version when you make backwards-compatible bug fixes.</li>
        <li>Additional labels for pre-release and build metadata are available as extensions to the MAJOR.MINOR.PATCH format.</li>
    </ul>

    <p>More information is available at <a href="http://semver.org">semver.org</a>.</p>


    <h2>Creating Versions</h2>

    <p>To create a version of your mod, simply create a tag with the version number. If you are using GitHub you can goto
        <em>Releases</em> then click <em>Create a new relese</em>.</p>


    <h2>Dependancy Versions</h2>

    <ul>
        <li><code>1.2.3</code> - requires an exact version.</li>
        <li><code>^1.2.3</code> or <code>>=1.2.3 <2.0.0</code> - requires version
            <code>1.2.3</code> or above, but less than <code>2.0.0</code>.
        </li>
        <li><code>~1.2.3</code> or <code>>=1.2.3 <1.3.0</code> - requires version
            <code>1.2.3</code> or above, but less than <code>1.3.0</code>.
        </li>
    </ul>

    <p>More information is available at <a href="https://github.com/npm/node-semver">node-semver</a>.</p>


    <h2>Notes</h2>

    <p>Any version below <code>1.0.0</code> is considered alpha and may contain incompatible API changes.</p>

</div>

src/views/docs/update-webhook.php
<?php
/* @var $this yii\web\View */

use yii\helpers\Html;
use yii\helpers\Url;

$this->title = 'Update Webhook';
$this->params['breadcrumbs'][] = ['label' => 'Docs', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="docs-github-webhook">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>Adding a webhook to your repository will update minetest-bower with the latest information each time you push a
        change.</p>

    <h2>GitHub</h2>

    <p>Create a new webhook and enter
        <code><?= Url::to(['update', 'name' => 'YOUR_MOD_NAME'], true); ?></code> into the
        <em>Payload URL</em>, then click <em>Add webhook</em>.</p>
    <?= Html::img('https://cloud.githubusercontent.com/assets/51875/9213435/7cf27a68-40d1-11e5-888a-c4692ad9f4b9.png'); ?>

    <h2>BitBucket</h2>

    <p>Create a new webhook and enter
        <code><?= Url::to(['update', 'name' => 'YOUR_MOD_NAME'], true); ?></code> into the URL. </p>
    <?= Html::img('https://cloud.githubusercontent.com/assets/51875/9217084/5f2da65c-4102-11e5-81b5-61b313a39aa7.png'); ?>

</div>