src/controllers/ModController.php
<?php

namespace app\controllers;

use app\components\Git;
use Yii;
use app\models\Package;
use app\models\search\PackageSearch;
use yii\db\Expression;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * ModController implements the CRUD actions for Package model.
 */
class ModController extends Controller
{
    /**
     * @var bool
     */
    public $enableCsrfValidation = false;

    /**
     * Browse Package models.
     * @return mixed
     */
    //public function actionIndex()
    //{
    //    $searchModel = new PackageSearch();
    //    $dataProvider = $searchModel->search(['PackageSearch' => Yii::$app->request->queryParams]);
    //
    //    return $this->render('index', [
    //        'searchModel' => $searchModel,
    //        'dataProvider' => $dataProvider,
    //    ]);
    //}

    /**
     * Redirects to a random mod.
     * @return mixed
     */
    //public function actionRandom()
    //{
    //    $driver = Package::getDb()->driverName;
    //    if ($driver == 'mysql') {
    //        $rand = new Expression('RAND()');
    //    } elseif ($driver == 'pgsql') {
    //        $rand = new Expression('RANDOM()');
    //    } else {
    //        return $this->redirect(['index']);
    //    }
    //    $model = Package::find()->orderBy($rand)->one();
    //    return $this->redirect(['view', 'name' => $model->name]);
    //}

    /**
     * Displays a single Package model.
     * @param string $name
     * @return mixed
     * @throws NotFoundHttpException
     */
    public function actionView($name)
    {
        $model = $this->findModel($name);

        // add a hit once per user per 24 hours
        $cacheKey = $model->name . '_' . Yii::$app->request->userIP;
        if (!Yii::$app->cache->get($cacheKey)) {
            Yii::$app->cache->set($cacheKey, true, (60 * 60 * 24));
            $model->hits++;
            $model->save(false, ['hits']);
        }

        return $this->render('view', [
            'model' => $model,
        ]);
    }

    /**
     * Displays a single Package models bower info.
     * @param string $name
     * @return mixed
     * @throws NotFoundHttpException
     */
    public function actionBower($name)
    {
        $model = $this->findModel($name);
        return $this->render('bower', [
            'model' => $model,
        ]);
    }

    /**
     * Displays a single Package models readme info.
     * @param string $name
     * @return mixed
     * @throws NotFoundHttpException
     */
    public function actionReadme($name)
    {
        $model = $this->findModel($name);
        return $this->render('readme', [
            'model' => $model,
        ]);
    }

    /**
     * Displays a single Package models readme info.
     * @param string $name
     * @return mixed
     * @throws NotFoundHttpException
     */
    public function actionScreenshots($name)
    {
        $model = $this->findModel($name);
        return $this->render('screenshots', [
            'model' => $model,
        ]);
    }

    /**
     * Creates a new Package model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Package();

        if ($model->load(Yii::$app->request->post()) && $model->harvestModInfo() && $model->save()) {
            Yii::$app->getSession()->setFlash('success', Yii::t('app', 'Mod has been registered.'));
            return $this->redirect(['view', 'name' => $model->name]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Package model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param string $name
     * @return mixed
     * @throws NotFoundHttpException
     * @throws \Exception
     * @throws \Throwable
     * @throws \yii\db\StaleObjectException
     */
    public function actionUpdate($name)
    {
        $model = $this->findModel($name);
        if (Git::getFile($model->url)) {
            $model->harvestModInfo();
            if ($model->getDirtyAttributes()) {
                if ($model->save()) {
                    Yii::$app->getSession()->setFlash('success', Yii::t('app', 'Mod has been updated from remote repository.'));
                } else {
                    Yii::$app->getSession()->setFlash('danger', Yii::t('app', 'Error while saving mod updates.'));
                }
            } else {
                Yii::$app->getSession()->setFlash('info', Yii::t('app', 'Mod has been updated from remote repository, however no change was detected.'));
            }
            return $this->redirect(['view', 'name' => $model->name]);
        }
        $model->delete();
        Yii::$app->getSession()->setFlash('danger', Yii::t('app', 'Mod source could not be found updated so mod was deleted.'));
        return $this->redirect(Yii::$app->homeUrl);
    }


    /**
     * Renders a tag cloud of popular keywords
     * @return mixed
     */
    //public function actionCloud()
    //{
    //    $keywords = Yii::$app->cache->get('mod.cloud.keywords');
    //    if (!$keywords) {
    //        $keywords = [];
    //        $packages = Package::find()->where(['is not', 'keywords', null])->all();
    //        foreach ($packages as $package) {
    //            foreach (explode(',', $package->keywords) as $keyword) {
    //                if (!isset($keywords[$keyword])) {
    //                    $keywords[$keyword] = [
    //                        'text' => $keyword,
    //                        'weight' => 0,
    //                        'link' => Url::to(['/mod/index', 'search' => $keyword]),
    //                    ];
    //                }
    //                $keywords[$keyword]['weight']++;
    //            }
    //        }
    //        Yii::$app->cache->set('mod.cloud.keywords', $keywords, 60 * 60);
    //    }
    //    return $this->render('cloud', ['keywords' => $keywords]);
    //}

    /**
     * Finds the Package model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param string $name
     * @return Package the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($name)
    {
        if (($model = Package::find()->where(['name' => $name])->one()) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

src/controllers/PackageController.php
<?php

namespace app\controllers;

use app\components\Git;
use app\models\Package;
use Yii;
use yii\filters\VerbFilter;
use yii\web\Controller;
use yii\web\HttpException;
use yii\web\Response;

/**
 * Class PackageController
 * @package app\controllers
 */
class PackageController extends Controller
{
    /**
     * @var bool
     */
    public $enableCsrfValidation = false;

    /**
     * @return array
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'create' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @param \yii\base\Action $action
     * @return bool
     * @throws \yii\web\BadRequestHttpException
     */
    public function beforeAction($action)
    {
        Yii::$app->response->format = Response::FORMAT_JSON;
        return parent::beforeAction($action);
    }

    /**
     * @return \app\models\Package[]|array
     */
    public function actionIndex()
    {
        return Package::find()
            ->select(['name', 'url', 'hits'])
            ->orderBy(['hits' => SORT_DESC])
            ->all();
    }

    /**
     * @param $name
     * @return Package|array|null
     * @throws HttpException
     */
    public function actionView($name)
    {
        $package = Package::find()
            ->where(['name' => $name])
            ->one();
        if ($package) {

            // add a hit once per user per 24 hours
            $cacheKey = $package->name . '_' . Yii::$app->request->userIP;
            if (!Yii::$app->cache->get($cacheKey)) {
                Yii::$app->cache->set($cacheKey, true, (60 * 60 * 24));
                $package->hits++;
                $package->save(false, ['hits']);
            }

            return $package;
        }
        throw new HttpException(404, 'Package not found.');
    }

    /**
     * @param $search
     * @return \app\models\Package[]|array
     */
    public function actionSearch($search)
    {
        return Package::find()
            ->select(['name', 'url', 'hits'])
            ->where([
                'or',
                ['like', 'name', $search],
                ['like', 'keywords', $search],
            ])
            ->orderBy(['hits' => SORT_DESC])
            ->all();
    }

    /**
     * @return string
     * @throws HttpException
     */
    public function actionCreate()
    {
        $package = new Package();
        $package->setAttributes(Yii::$app->request->post());
        $package->harvestModInfo();
        if ($package->save()) {
            Yii::$app->response->statusCode = 201;
            return '';
        }
        foreach ($package->errors as $attributeErrors) {
            foreach ($attributeErrors as $error) {
                if (strpos($error, 'has already been taken')) {
                    throw new HttpException(403, 'Package already registered');
                }
            }
        }
        if (isset($package->errors['name'])) {
            throw new HttpException(400, 'Invalid Name: ' . implode(', ', $package->errors['name']));
        }
        if (isset($package->errors['url'])) {
            throw new HttpException(400, 'Invalid URL: ' . implode(', ', $package->errors['url']));
        }
        $errors = [];
        foreach ($package->errors as $attribute => $attributeErrors) {
            foreach ($attributeErrors as $error) {
                $errors[] = $attribute . ': ' . $error;
            }
        }
        throw new HttpException(400, 'Error: ' . implode(', ', $errors));
    }

}

src/controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\web\Controller;

class SiteController extends Controller
{

    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    public function actionIndex()
    {
        return $this->render('index');
    }

}

src/views/site/_index-jumbotron.php
<?php
/* @var $this \yii\web\View */

use yii\helpers\Html;
use yii\helpers\Url;

?>

<div class="jumbotron">
    <div class="container">
        <?= Html::img(Yii::getAlias('@web') . '/logo.png', [
            'id' => 'logo',
            'class' => 'pull-left',
        ]) ?>
        <div>
            <h1><?= Yii::$app->name; ?></h1>

            <p>A mod repository and package manager for Minetest.</p>
        </div>

        <!--
        <p>
            <a class="btn btn-success btn-lg" href="<?= Url::to(['/audit']); ?>" role="button">Getting Started</a>
        </p>
        -->
    </div>
</div>

src/views/site/_mod-view.php
<?php

use app\widgets\DetailView;
use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Package */

?>
<div class="col-md-3 site-mod-view">

    <div class="thumbnail">
        <?php
        if ($model->screenshots) {
            echo Html::a(Html::img($model->screenshots[0]), ['/mod/view', 'name' => $model->name]);
        } else {
            echo Html::a(Html::img('@web/img/no-image.png'), ['/mod/view', 'name' => $model->name]);
        }
        ?>
        <div class="caption">
            <h3><?= Html::a(Html::encode($model->name), ['/mod/view', 'name' => $model->name]) ?></h3>

            <p><?= $model->description; ?></p>

            <p><?= $model->getLinksHtml(); ?></p>
        </div>
    </div>
</div>

src/views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

src/views/site/index.php
<?php

/* @var $this yii\web\View */

use app\models\Package;
use app\models\search\PackageSearch;
use yii\data\ActiveDataProvider;
use yii\data\ArrayDataProvider;
use yii\data\Pagination;
use yii\db\Expression;
use yii\helpers\Html;
use yii\widgets\ListView;

$this->title = 'Minetest Mods: The Minetest mod repository.';
$this->params['jumbotron'] = '/site/_index-jumbotron';

?>
<div class="site-index">

    <div class="body-content">

        <p>Minetest Mods is a Minetest mod repository. The repository is unmoderated, anybody may
            <?= Html::a('submit a mod', ['mod/create']) ?>.
            Different versions by different people of similar mods are permitted but each version must have a different
            name. A mod can be deleted by deleting the source repo and then clicking update from the mod page.</p>

        <p>If you'd like to run a Minetest Mods mirror, this is encouraged and simple to set up. Simply copy
            the <?= Html::a('this JSON file', ['package/index']) ?> to your website and update it periodically.</p>

        <?php
        //echo '<h2>Search Mods</h2>';
        //echo $this->render('/mod/_search', ['model' => new PackageSearch()]);
        ?>

        <hr>

        <?php
        echo '<div class="text-justify">';
        $items = [];
        foreach (\app\models\Package::find()->orderBy(['name' => SORT_ASC])->all() as $package) {
            $items[] = Html::a($package->name, ['mod/view', 'name' => $package->name]);
        }
        echo Html::ul($items, [
            'encode' => false,
            'class' => 'list-inline',
        ]);
        echo '</div>';
        //echo '<div class="row">';
        //$searchModel = new PackageSearch();
        //$query = Package::find();
        //$driver = Package::getDb()->driverName;
        //if ($driver == 'mysql') {
        //    $rand = new Expression('RAND()');
        //} elseif ($driver == 'pgsql') {
        //    $rand = new Expression('RANDOM()');
        //}
        //if (isset($rand)) {
        //    $query->orderBy($rand);
        //}
        //$query->limit(4);
        //$pagination = new Pagination(['totalCount' => 4]);
        //$pagination->pageSize = 4;
        //$pagination->pageSizeLimit = [4];
        //echo ListView::widget([
        //    'layout' => '{items}',
        //    'dataProvider' => new ArrayDataProvider(['allModels' => $query->all()]),
        //    'itemOptions' => ['class' => 'item'],
        //    'itemView' => function ($model, $key, $index, $widget) {
        //        return $this->render('_mod-view', ['model' => $model]);
        //    },
        //    'pager' => $pagination,
        //]);
        //echo '</div>';
        ?>

    </div>
</div>