src/controllers/DocsController.php
<?php

namespace app\controllers;

use Yii;
use yii\web\Controller;

class DocsController extends Controller
{

    public function actionIndex()
    {
        return $this->render('index');
    }

    public function actionBowerCli()
    {
        return $this->render('bower-cli');
    }

    public function actionBowerFormat()
    {
        return $this->render('bower-format');
    }

    public function actionUpdateWebhook()
    {
        return $this->render('update-webhook');
    }

    public function actionRegistryCurl()
    {
        return $this->render('registry-curl');
    }

    public function actionSemver()
    {
        return $this->render('semver');
    }

}

src/controllers/ModController.php
<?php

namespace app\controllers;

use app\components\Git;
use Yii;
use app\models\Package;
use app\models\search\PackageSearch;
use yii\db\Expression;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * ModController implements the CRUD actions for Package model.
 */
class ModController extends Controller
{
    /**
     * @var bool
     */
    public $enableCsrfValidation = false;

    /**
     * Browse Package models.
     * @return mixed
     */
    //public function actionIndex()
    //{
    //    $searchModel = new PackageSearch();
    //    $dataProvider = $searchModel->search(['PackageSearch' => Yii::$app->request->queryParams]);
    //
    //    return $this->render('index', [
    //        'searchModel' => $searchModel,
    //        'dataProvider' => $dataProvider,
    //    ]);
    //}

    /**
     * Redirects to a random mod.
     * @return mixed
     */
    //public function actionRandom()
    //{
    //    $driver = Package::getDb()->driverName;
    //    if ($driver == 'mysql') {
    //        $rand = new Expression('RAND()');
    //    } elseif ($driver == 'pgsql') {
    //        $rand = new Expression('RANDOM()');
    //    } else {
    //        return $this->redirect(['index']);
    //    }
    //    $model = Package::find()->orderBy($rand)->one();
    //    return $this->redirect(['view', 'name' => $model->name]);
    //}

    /**
     * Displays a single Package model.
     * @param string $name
     * @return mixed
     * @throws NotFoundHttpException
     */
    public function actionView($name)
    {
        $model = $this->findModel($name);

        // add a hit once per user per 24 hours
        $cacheKey = $model->name . '_' . Yii::$app->request->userIP;
        if (!Yii::$app->cache->get($cacheKey)) {
            Yii::$app->cache->set($cacheKey, true, (60 * 60 * 24));
            $model->hits++;
            $model->save(false, ['hits']);
        }

        return $this->render('view', [
            'model' => $model,
        ]);
    }

    /**
     * Displays a single Package models bower info.
     * @param string $name
     * @return mixed
     * @throws NotFoundHttpException
     */
    public function actionBower($name)
    {
        $model = $this->findModel($name);
        return $this->render('bower', [
            'model' => $model,
        ]);
    }

    /**
     * Displays a single Package models readme info.
     * @param string $name
     * @return mixed
     * @throws NotFoundHttpException
     */
    public function actionReadme($name)
    {
        $model = $this->findModel($name);
        return $this->render('readme', [
            'model' => $model,
        ]);
    }

    /**
     * Displays a single Package models readme info.
     * @param string $name
     * @return mixed
     * @throws NotFoundHttpException
     */
    public function actionScreenshots($name)
    {
        $model = $this->findModel($name);
        return $this->render('screenshots', [
            'model' => $model,
        ]);
    }

    /**
     * Creates a new Package model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Package();

        if ($model->load(Yii::$app->request->post()) && $model->harvestModInfo() && $model->save()) {
            Yii::$app->getSession()->setFlash('success', Yii::t('app', 'Mod has been registered.'));
            return $this->redirect(['view', 'name' => $model->name]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Package model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param string $name
     * @return mixed
     * @throws NotFoundHttpException
     * @throws \Exception
     * @throws \Throwable
     * @throws \yii\db\StaleObjectException
     */
    public function actionUpdate($name)
    {
        $model = $this->findModel($name);
        if (Git::getFile($model->url)) {
            $model->harvestModInfo();
            if ($model->getDirtyAttributes()) {
                if ($model->save()) {
                    Yii::$app->getSession()->setFlash('success', Yii::t('app', 'Mod has been updated from remote repository.'));
                } else {
                    Yii::$app->getSession()->setFlash('danger', Yii::t('app', 'Error while saving mod updates.'));
                }
            } else {
                Yii::$app->getSession()->setFlash('info', Yii::t('app', 'Mod has been updated from remote repository, however no change was detected.'));
            }
            return $this->redirect(['view', 'name' => $model->name]);
        }
        $model->delete();
        Yii::$app->getSession()->setFlash('danger', Yii::t('app', 'Mod source could not be found updated so mod was deleted.'));
        return $this->redirect(Yii::$app->homeUrl);
    }


    /**
     * Renders a tag cloud of popular keywords
     * @return mixed
     */
    //public function actionCloud()
    //{
    //    $keywords = Yii::$app->cache->get('mod.cloud.keywords');
    //    if (!$keywords) {
    //        $keywords = [];
    //        $packages = Package::find()->where(['is not', 'keywords', null])->all();
    //        foreach ($packages as $package) {
    //            foreach (explode(',', $package->keywords) as $keyword) {
    //                if (!isset($keywords[$keyword])) {
    //                    $keywords[$keyword] = [
    //                        'text' => $keyword,
    //                        'weight' => 0,
    //                        'link' => Url::to(['/mod/index', 'search' => $keyword]),
    //                    ];
    //                }
    //                $keywords[$keyword]['weight']++;
    //            }
    //        }
    //        Yii::$app->cache->set('mod.cloud.keywords', $keywords, 60 * 60);
    //    }
    //    return $this->render('cloud', ['keywords' => $keywords]);
    //}

    /**
     * Finds the Package model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param string $name
     * @return Package the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($name)
    {
        if (($model = Package::find()->where(['name' => $name])->one()) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

src/views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use app\widgets\Alert;
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<?php
NavBar::begin([
    'brandLabel' => 'Minetest Mods',
    'brandUrl' => Yii::$app->homeUrl,
    'options' => [
        'class' => 'navbar-default navbar-fixed-top',
    ],
]);
echo '<a class="hidden-xs" href="https://github.com/cornernote/minetest-bower"><img style="position: absolute; top: 0; right: 0; border: 0; z-index: 1;" src="https://s3.amazonaws.com/github/ribbons/forkme_right_darkblue_121621.png" alt="Fork me on GitHub"></a>';
echo Nav::widget([
    'options' => ['class' => 'navbar-nav'],
    'items' => [
        //['label' => 'Browse', 'url' => ['/mod/index'], 'active' => (Yii::$app->controller->id == 'mod' && !in_array(Yii::$app->controller->action->id, ['create', 'cloud']))],
        //['label' => 'Random', 'url' => ['/mod/random']],
        //['label' => 'Cloud', 'url' => ['/mod/cloud']],
        ['label' => 'Submit', 'url' => ['/mod/create']],
        ['label' => 'Docs', 'url' => ['/docs/index'], 'active' => Yii::$app->controller->id == 'docs'],
    ],
]);
echo Nav::widget([
    'options' => ['class' => 'navbar-nav navbar-right'],
    'items' => [
        ['label' => 'Minetest Home', 'url' => 'http://minetest.net'],
    ],
]);
NavBar::end();

if (isset($this->params['jumbotron'])) {
    echo $this->render($this->params['jumbotron']);
}
?>

<div class="container">
    <?= Breadcrumbs::widget([
        'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
    ]) ?>
    <?= Alert::widget() ?>
    <?= $content ?>
</div>

<footer class="footer">
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <p class="text-muted">
                    Have issues or questions?
                    <a href="https://github.com/cornernote/minetest-bower/issues/new">Contact us</a>
                </p>
            </div>
            <div class="col-md-6 text-right">
                <p class="text-muted">
                    Hosting sponsored by
                    <a href="https://heroku.com/">Heroku</a>
                </p>
            </div>
        </div>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>